# Generated by Django 4.1.2 on 2022-10-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('1', 'Web'), ('2', 'Marketing'), ('3', 'Copyrating'), ('4', 'Rerating'), ('5', 'Translate'), ('6', 'Video'), ('7', 'Photo')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('1', 'Web'), ('2', 'Marketing'), ('3', 'Copyrating'), ('4', 'Rerating'), ('5', 'Translate'), ('6', 'Video'), ('7', 'Photo')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Middle'), ('3', 'High')], default='1', max_length=1),
        ),
    ]
